"""Added  tables

Revision ID: 71e120112b2f
Revises: 
Create Date: 2022-11-16 23:34:41.608574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e120112b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('currency',
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('num_code', sa.Integer(), nullable=True),
    sa.Column('char_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('currency_id')
    )
    op.create_index(op.f('ix_currency_currency_id'), 'currency', ['currency_id'], unique=False)
    op.create_table('currency_rate',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_captured', sa.DateTime(), nullable=True),
    sa.Column('currency_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.currency_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rate')
    op.drop_index(op.f('ix_currency_currency_id'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
